### PR TITLE
refactor: update nestjs dependencies

### PR DESCRIPTION
**Pull request by mahsumurebe**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #516 

## Does this PR introduce a breaking change?

- * [ ] Yes
- * [x]  No

### CODE REVIEW

**Comment by pneme** [comment]
Any estimate for merging this? My team is excited for SWC support in v10 Nest.js for which this bump is needed 🙏

**Review by mahsumurebe — COMMENTED** [review]
Any news ?

**Review by renatoaug — APPROVED** [review]

**Comment by v-petukhov** [comment]
Hey @liaoliaots ! Any updates?

**Comment by andresemartinez** [comment]
@mahsumurebe, I think this PR should also update the requiremenets in the readme for Nest and Node

**Comment by satanshiro** [comment]
any news? it has been some time since last commit is this maintained? @liaoliaots

**Comment by mahsumurebe** [comment]
Hi @liaoliaots 

Necessary improvements have been made. Can you check the pull request?

**Comment by heiba** [comment]
@liaoliaots Would much appreciate your support on this. We're kind of blocked on upgrading to Nest.js v10 because of the nestjs-redis not supporting it. Anything I can do from my side, I will be glad to support. I thank you for your efforts on this project.

**Comment by jorcelinojunior** [comment]
Hi @liaoliaots 

Can you check the pull request?

**Comment by satanshiro** [comment]
it's been close to 2 months now, is it time to create a fork instead?

**Comment by v-petukhov** [comment]
> it's been close to 2 months now, is it time to create a fork instead?

It's already created by @Songkeys

https://github.com/liaoliaots/nestjs-redis/issues/516#issuecomment-1626898431

**Comment by dougal83** [comment]
It is possible to override dependencies in `package.json` but do so at your own risk.  The following worked via npm:

```` 
"overrides": {
    "@liaoliaots/nestjs-redis": {
      "@nestjs/common": "$@nestjs/common",
      "@nestjs/core": "$@nestjs/core"
    }
},
  ````

**Comment by liaoliaots** [comment]
Please check out the new version: version 10 of [@liaoliaots/nestjs-redis](https://www.npmjs.com/package/@liaoliaots/nestjs-redis/v/10.0.0).

**Pull request closed without merging**
