### PR TITLE
update nestjs peer dependencies to v10

### PR DESCRIPTION
**Pull request by duysolo**
## PR Type

Update peer dependencies of `@nestjs` to the latest version (v10).

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

NestJS recently released version 10 approximately two weeks ago, resulting in our project encountering the following warning:

```
─┬ @liaoliaots/nestjs-redis 9.0.5
│ ├── ✕ unmet peer @nestjs/common@^9.0.0: found 10.0.4
│ └── ✕ unmet peer @nestjs/core@^9.0.0: found 10.0.4
```

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by duysolo** [comment]
@liaoliaots could you have a look on this?

**Comment by mahsumurebe** [comment]
Hi @duysolo 

I have a PR that I opened eighteen days ago. It has not been checked yet.

You can follow PR #517

**Comment by hotsezus** [comment]
@mahsumurebe it looks like we also need to upgrade node.js required version to 16 based on [NestJS Migration Guide](https://docs.nestjs.com/migration-guide#dropping-support-for-nodejs-v12)

**Comment by hotsezus** [comment]
Actually, it looks like [!518](https://github.com/liaoliaots/nestjs-redis/pull/518) is actually more acurate beacause it does update everything needed and introduces major update to package

**Comment by mahsumurebe** [comment]
I’ve already changed the nodejs required version. Please check [this](https://github.com/liaoliaots/nestjs-redis/pull/517/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R61)

**Comment by jorcelinojunior** [comment]
Hi @liaoliaots 

Can you check the pull request?

**Comment by bistacos** [comment]
Hey @liaoliaots , can you take a look here?

**Comment by evyros** [comment]
Looking forward to this one, it's blocking us from upgrading to v10

**Comment by Johannes-Schiel** [comment]
How is the state of this ?

**Comment by Beni312** [comment]
any update? I need this upgrade

**Comment by bistacos** [comment]
@Beni312 The repo owner is not making updates, I've removed `nestjs-redis` from my dependencies and rolled my own RedisService using `ioredis`:

```typescript
import { Injectable, Logger, OnModuleDestroy } from '@nestjs/common';
import { Redis } from 'ioredis';
import { RedisException } from './redis.exception';

@Injectable()
export class RedisService implements OnModuleDestroy {
  private client: Redis | undefined; // undefined bc it might not exist due to lazy connect

  private createClient() {
    this.client = new Redis({
      host: process.env.REDIS_HOST,
      port: Number(process.env.REDIS_PORT),
      password: process.env.REDIS_PASSWORD,
      retryStrategy: (times: number) => {
        if (times > 10) {
          return undefined;
        }
        // retry at longer intervals based on the number of retries so far, max 3 seconds
        return Math.min(times * 100, 3000);
      },
    });

    if (!this.client) {
      throw new RedisException('Could not connect to Redis');
    }

    this.client.on('error', (error) => {
      Logger.error(`Redis error: ${error}`);
    });

    return this.client;
  }

  getClient(): Redis {
    if (!this.client) {
      this.createClient(); // lazy connect
    }
    return this.client;
  }

  async onModuleDestroy() {
    if (this.client) {
      return new Promise((resolve, reject) => {
        this.client?.quit((err, reply) => {
          if (err) {
            return reject(err);
          }
          resolve(reply);
        });
      });
    }
  }
}
```

...usable like so

```typescript
import { RedisService } from 'src/redis/redis.service';

export class YourClass {
  constructor(
    private readonly redisService: RedisService,
  ) {
  // ...
  }
}
  
 async yourFunction() {
   const redis = this.redisService.getClient();
   await redis.set(
     // see ioredis documentation for basic usage
   );
 } 
```

Hope that helps.

**Comment by Beni312** [comment]
> @Beni312 The repo owner is not making updates, I've removed `nestjs-redis` from my dependencies and rolled my own RedisService using `ioredis`:
> 
> ```ts
> import { Injectable, Logger, OnModuleDestroy } from '@nestjs/common';
> import { Redis } from 'ioredis';
> import { RedisException } from './redis.exception';
> 
> @Injectable()
> export class RedisService implements OnModuleDestroy {
>   private client: Redis | undefined; // undefined bc it might not exist due to lazy connect
> 
>   private createClient() {
>     this.client = new Redis({
>       host: process.env.REDIS_HOST,
>       port: Number(process.env.REDIS_PORT),
>       password: process.env.REDIS_PASSWORD,
>       retryStrategy: (times: number) => {
>         if (times > 10) {
>           return undefined;
>         }
>         // retry at longer intervals based on the number of retries so far, max 3 seconds
>         return Math.min(times * 100, 3000);
>       },
>     });
> 
>     if (!this.client) {
>       throw new RedisException('Could not connect to Redis');
>     }
> 
>     this.client.on('error', (error) => {
>       Logger.error(`Redis error: ${error}`);
>     });
> 
>     return this.client;
>   }
> 
>   getClient(): Redis {
>     if (!this.client) {
>       this.createClient(); // lazy connect
>     }
>     return this.client;
>   }
> 
>   async onModuleDestroy() {
>     if (this.client) {
>       return new Promise((resolve, reject) => {
>         this.client?.quit((err, reply) => {
>           if (err) {
>             return reject(err);
>           }
>           resolve(reply);
>         });
>       });
>     }
>   }
> }
> ```
> 
> ...usable like so
> 
> ```ts
> import { RedisService } from 'src/redis/redis.service';
> 
> export class YourClass {
>   constructor(
>     private readonly redisService: RedisService,
>   ) {
>   // ...
>   }
> }
>   
>  async yourFunction() {
>    const redis = this.redisService.getClient();
>    await redis.set(
>      // see ioredis documentation for basic usage
>    );
>  } 
> ```
> 
> Hope that helps.

I put it in my application, works well, thanks :)

**Comment by liaoliaots** [comment]
Please check out the new version: version 10 of [@liaoliaots/nestjs-redis](https://www.npmjs.com/package/@liaoliaots/nestjs-redis/v/10.0.0).

**Pull request closed without merging**
